version: '3.3'

services:
  db:
    container_name: PDV_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: sistema-pdv
      POSTGRES_USER: sistema-pdv
      POSTGRES_DB: sistema-pdv
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data